// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: snffr.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnifferService_Monitor_FullMethodName = "/snffr.SnifferService/Monitor"
)

// SnifferServiceClient is the client API for SnifferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnifferServiceClient interface {
	// Bidirectional streaming:
	// Agent sends a stream of PacketReports
	// Manager sends a stream of ActionCommands
	Monitor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PacketReport, ActionCommand], error)
}

type snifferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnifferServiceClient(cc grpc.ClientConnInterface) SnifferServiceClient {
	return &snifferServiceClient{cc}
}

func (c *snifferServiceClient) Monitor(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PacketReport, ActionCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SnifferService_ServiceDesc.Streams[0], SnifferService_Monitor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PacketReport, ActionCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnifferService_MonitorClient = grpc.BidiStreamingClient[PacketReport, ActionCommand]

// SnifferServiceServer is the server API for SnifferService service.
// All implementations must embed UnimplementedSnifferServiceServer
// for forward compatibility.
type SnifferServiceServer interface {
	// Bidirectional streaming:
	// Agent sends a stream of PacketReports
	// Manager sends a stream of ActionCommands
	Monitor(grpc.BidiStreamingServer[PacketReport, ActionCommand]) error
	mustEmbedUnimplementedSnifferServiceServer()
}

// UnimplementedSnifferServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnifferServiceServer struct{}

func (UnimplementedSnifferServiceServer) Monitor(grpc.BidiStreamingServer[PacketReport, ActionCommand]) error {
	return status.Error(codes.Unimplemented, "method Monitor not implemented")
}
func (UnimplementedSnifferServiceServer) mustEmbedUnimplementedSnifferServiceServer() {}
func (UnimplementedSnifferServiceServer) testEmbeddedByValue()                        {}

// UnsafeSnifferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnifferServiceServer will
// result in compilation errors.
type UnsafeSnifferServiceServer interface {
	mustEmbedUnimplementedSnifferServiceServer()
}

func RegisterSnifferServiceServer(s grpc.ServiceRegistrar, srv SnifferServiceServer) {
	// If the following call panics, it indicates UnimplementedSnifferServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnifferService_ServiceDesc, srv)
}

func _SnifferService_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SnifferServiceServer).Monitor(&grpc.GenericServerStream[PacketReport, ActionCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SnifferService_MonitorServer = grpc.BidiStreamingServer[PacketReport, ActionCommand]

// SnifferService_ServiceDesc is the grpc.ServiceDesc for SnifferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnifferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snffr.SnifferService",
	HandlerType: (*SnifferServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _SnifferService_Monitor_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "snffr.proto",
}
