// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: snffr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionCommand_ActionType int32

const (
	ActionCommand_BLOCK      ActionCommand_ActionType = 0
	ActionCommand_RATE_LIMIT ActionCommand_ActionType = 1
	ActionCommand_ALLOW      ActionCommand_ActionType = 2
)

// Enum value maps for ActionCommand_ActionType.
var (
	ActionCommand_ActionType_name = map[int32]string{
		0: "BLOCK",
		1: "RATE_LIMIT",
		2: "ALLOW",
	}
	ActionCommand_ActionType_value = map[string]int32{
		"BLOCK":      0,
		"RATE_LIMIT": 1,
		"ALLOW":      2,
	}
)

func (x ActionCommand_ActionType) Enum() *ActionCommand_ActionType {
	p := new(ActionCommand_ActionType)
	*p = x
	return p
}

func (x ActionCommand_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionCommand_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_snffr_proto_enumTypes[0].Descriptor()
}

func (ActionCommand_ActionType) Type() protoreflect.EnumType {
	return &file_snffr_proto_enumTypes[0]
}

func (x ActionCommand_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionCommand_ActionType.Descriptor instead.
func (ActionCommand_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_snffr_proto_rawDescGZIP(), []int{1, 0}
}

// The metadata for a single captured packet
type PacketReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	SrcIp         string                 `protobuf:"bytes,2,opt,name=src_ip,json=srcIp,proto3" json:"src_ip,omitempty"`
	DstIp         string                 `protobuf:"bytes,3,opt,name=dst_ip,json=dstIp,proto3" json:"dst_ip,omitempty"`
	SrcPort       uint32                 `protobuf:"varint,4,opt,name=src_port,json=srcPort,proto3" json:"src_port,omitempty"`
	DstPort       uint32                 `protobuf:"varint,5,opt,name=dst_port,json=dstPort,proto3" json:"dst_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`                          // e.g., "TCP", "UDP", "ICMP"
	Length        uint32                 `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`                             // Size of the packet in bytes
	PayloadPeek   []byte                 `protobuf:"bytes,8,opt,name=payload_peek,json=payloadPeek,proto3" json:"payload_peek,omitempty"` // First few bytes for signature matching
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketReport) Reset() {
	*x = PacketReport{}
	mi := &file_snffr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketReport) ProtoMessage() {}

func (x *PacketReport) ProtoReflect() protoreflect.Message {
	mi := &file_snffr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketReport.ProtoReflect.Descriptor instead.
func (*PacketReport) Descriptor() ([]byte, []int) {
	return file_snffr_proto_rawDescGZIP(), []int{0}
}

func (x *PacketReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PacketReport) GetSrcIp() string {
	if x != nil {
		return x.SrcIp
	}
	return ""
}

func (x *PacketReport) GetDstIp() string {
	if x != nil {
		return x.DstIp
	}
	return ""
}

func (x *PacketReport) GetSrcPort() uint32 {
	if x != nil {
		return x.SrcPort
	}
	return 0
}

func (x *PacketReport) GetDstPort() uint32 {
	if x != nil {
		return x.DstPort
	}
	return 0
}

func (x *PacketReport) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *PacketReport) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *PacketReport) GetPayloadPeek() []byte {
	if x != nil {
		return x.PayloadPeek
	}
	return nil
}

func (x *PacketReport) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// A command sent from the Manager to the Agent
type ActionCommand struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Action          ActionCommand_ActionType `protobuf:"varint,1,opt,name=action,proto3,enum=snffr.ActionCommand_ActionType" json:"action,omitempty"`
	TargetIp        string                   `protobuf:"bytes,2,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	Reason          string                   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	DurationSeconds uint32                   `protobuf:"varint,4,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // How long to keep the block active
	RateLimitPps    uint32                   `protobuf:"varint,5,opt,name=rate_limit_pps,json=rateLimitPps,proto3" json:"rate_limit_pps,omitempty"`        // Max packets per second (for RATE_LIMIT)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionCommand) Reset() {
	*x = ActionCommand{}
	mi := &file_snffr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCommand) ProtoMessage() {}

func (x *ActionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snffr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCommand.ProtoReflect.Descriptor instead.
func (*ActionCommand) Descriptor() ([]byte, []int) {
	return file_snffr_proto_rawDescGZIP(), []int{1}
}

func (x *ActionCommand) GetAction() ActionCommand_ActionType {
	if x != nil {
		return x.Action
	}
	return ActionCommand_BLOCK
}

func (x *ActionCommand) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *ActionCommand) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ActionCommand) GetDurationSeconds() uint32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *ActionCommand) GetRateLimitPps() uint32 {
	if x != nil {
		return x.RateLimitPps
	}
	return 0
}

var File_snffr_proto protoreflect.FileDescriptor

const file_snffr_proto_rawDesc = "" +
	"\n" +
	"\vsnffr.proto\x12\x05snffr\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x02\n" +
	"\fPacketReport\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x15\n" +
	"\x06src_ip\x18\x02 \x01(\tR\x05srcIp\x12\x15\n" +
	"\x06dst_ip\x18\x03 \x01(\tR\x05dstIp\x12\x19\n" +
	"\bsrc_port\x18\x04 \x01(\rR\asrcPort\x12\x19\n" +
	"\bdst_port\x18\x05 \x01(\rR\adstPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06length\x18\a \x01(\rR\x06length\x12!\n" +
	"\fpayload_peek\x18\b \x01(\fR\vpayloadPeek\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x82\x02\n" +
	"\rActionCommand\x127\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1f.snffr.ActionCommand.ActionTypeR\x06action\x12\x1b\n" +
	"\ttarget_ip\x18\x02 \x01(\tR\btargetIp\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12)\n" +
	"\x10duration_seconds\x18\x04 \x01(\rR\x0fdurationSeconds\x12$\n" +
	"\x0erate_limit_pps\x18\x05 \x01(\rR\frateLimitPps\"2\n" +
	"\n" +
	"ActionType\x12\t\n" +
	"\x05BLOCK\x10\x00\x12\x0e\n" +
	"\n" +
	"RATE_LIMIT\x10\x01\x12\t\n" +
	"\x05ALLOW\x10\x022J\n" +
	"\x0eSnifferService\x128\n" +
	"\aMonitor\x12\x13.snffr.PacketReport\x1a\x14.snffr.ActionCommand(\x010\x01B\x15Z\x13snffr/manager/protob\x06proto3"

var (
	file_snffr_proto_rawDescOnce sync.Once
	file_snffr_proto_rawDescData []byte
)

func file_snffr_proto_rawDescGZIP() []byte {
	file_snffr_proto_rawDescOnce.Do(func() {
		file_snffr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snffr_proto_rawDesc), len(file_snffr_proto_rawDesc)))
	})
	return file_snffr_proto_rawDescData
}

var file_snffr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_snffr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_snffr_proto_goTypes = []any{
	(ActionCommand_ActionType)(0), // 0: snffr.ActionCommand.ActionType
	(*PacketReport)(nil),          // 1: snffr.PacketReport
	(*ActionCommand)(nil),         // 2: snffr.ActionCommand
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_snffr_proto_depIdxs = []int32{
	3, // 0: snffr.PacketReport.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: snffr.ActionCommand.action:type_name -> snffr.ActionCommand.ActionType
	1, // 2: snffr.SnifferService.Monitor:input_type -> snffr.PacketReport
	2, // 3: snffr.SnifferService.Monitor:output_type -> snffr.ActionCommand
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_snffr_proto_init() }
func file_snffr_proto_init() {
	if File_snffr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snffr_proto_rawDesc), len(file_snffr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snffr_proto_goTypes,
		DependencyIndexes: file_snffr_proto_depIdxs,
		EnumInfos:         file_snffr_proto_enumTypes,
		MessageInfos:      file_snffr_proto_msgTypes,
	}.Build()
	File_snffr_proto = out.File
	file_snffr_proto_goTypes = nil
	file_snffr_proto_depIdxs = nil
}
